{% set version = '0.1.4' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pharmartf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pharmaRTF_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pharmaRTF/pharmaRTF_{{ version }}.tar.gz
  sha256: 2eb082ad88bcfc17bd6a08e2e937142feb054ed59a8839305fd5540a3dc926c0

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-assertthat >=0.2.1
    - r-huxtable >=4.7.1
    - r-purrr >=0.3.3
    - r-stringr >=1.4.0
  run:
    - r-base
    - r-assertthat >=0.2.1
    - r-huxtable >=4.7.1
    - r-purrr >=0.3.3
    - r-stringr >=1.4.0

test:
  commands:
    - $R -e "library('pharmaRTF')"           # [not win]
    - "\"%R%\" -e \"library('pharmaRTF')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=pharmaRTF
  license: MIT
  summary: Enhanced RTF wrapper written in R for use with existing R tables packages such as
    'Huxtable' or 'GT'. This package fills a gap where tables in certain packages can
    be written out to RTF, but cannot add certain metadata or features to the document
    that are required/expected in a report for a regulatory submission, such as multiple
    levels of titles and footnotes, making the document landscape, and controlling properties
    such as margins.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
